# Generated by Django 5.1 on 2024-08-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_showtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='movies/posters/'),
        ),
    ]
