# Generated by Django 5.1 on 2024-08-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        ("core", "0007_alter_showtime_film"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="tags",
            field=models.ManyToManyField(blank=True, to="blog.tag"),
        ),
    ]
