# Generated by Django 5.1 on 2024-08-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_film_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="omdb_response",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
