# Generated by Django 5.1 on 2024-09-08 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_film_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='tags',
        ),
    ]
