# Generated by Django 5.0.4 on 2024-05-16 12:48

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('default_hero_section', wagtail.blocks.StructBlock([('top_cta_action', wagtail.blocks.CharBlock()), ('top_cta_text', wagtail.blocks.CharBlock()), ('top_cta_link', wagtail.blocks.PageChooserBlock()), ('heading', wagtail.blocks.CharBlock()), ('body', wagtail.blocks.CharBlock()), ('btn_1_text', wagtail.blocks.CharBlock()), ('btn_1_page', wagtail.blocks.PageChooserBlock()), ('btn_2_text', wagtail.blocks.CharBlock()), ('btn_2_link', wagtail.blocks.URLBlock())])), ('cta_section_with_checklist', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock()), ('body', wagtail.blocks.ListBlock(child_block=wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock())]))), ('list_items', wagtail.blocks.ListBlock(child_block=wagtail.blocks.StructBlock([('item_text', wagtail.blocks.CharBlock())]))), ('btn_1_text', wagtail.blocks.CharBlock()), ('btn_1_page', wagtail.blocks.PageChooserBlock())]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='BlogAuthor',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.DeleteModel(
            name='BlogTag',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
