# Generated by Django 5.0.4 on 2024-04-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_post_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='avatar',
            field=models.ImageField(upload_to='static/img/blog_author/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='post',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/banner_images/%Y/%m'),
        ),
    ]
