# Generated by Django 5.2 on 2025-05-04 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_blogauthor_blogroll_moviereviewpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('imdb_id', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='moviereviewpage',
            name='post_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviereviewpage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reviews', to='website.blogauthor'),
        ),
        migrations.AddField(
            model_name='moviereviewpage',
            name='film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reviews', to='website.film'),
        ),
    ]
