# Generated by Django 5.2 on 2025-05-05 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_film_moviereviewpage_post_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviereviewpage",
            name="film",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="review",
                to="website.film",
            ),
        ),
    ]
