# Generated by Django 5.0.4 on 2024-05-20 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_blogauthor_blogpage_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('imdb_id', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterModelOptions(
            name='blogauthor',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='blogpage',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.movie'),
        ),
    ]
