# Generated by Django 5.0.4 on 2024-05-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_movie_alter_blogauthor_options_blogpage_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=models.TextField(),
        ),
    ]
