# Generated by Django 5.0.4 on 2024-04-20 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_movie_post_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='movie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.movie'),
        ),
    ]
