# Generated by Django 5.2 on 2025-05-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_schedule_showtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="start_date",
            field=models.DateField(),
        ),
    ]
