# Generated by Django 5.0.4 on 2024-04-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_post_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='omdb_response',
            field=models.JSONField(null=True),
        ),
    ]
