# Generated by Django 5.0.4 on 2024-05-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_movie_omdb_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='omdb_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
