# Generated by Django 5.0.4 on 2024-05-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
        ('website', '0011_genericpage_alter_movie_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenericPage',
            new_name='Membership',
        ),
    ]
