# Generated by Django 5.0.4 on 2024-06-14 22:57

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_supportpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('logo_hero', wagtail.blocks.StructBlock([])), ('default_hero_section', wagtail.blocks.StructBlock([('top_cta_action', wagtail.blocks.CharBlock()), ('top_cta_text', wagtail.blocks.CharBlock()), ('top_cta_link', wagtail.blocks.PageChooserBlock()), ('heading', wagtail.blocks.CharBlock()), ('body', wagtail.blocks.CharBlock()), ('btn_1_text', wagtail.blocks.CharBlock()), ('btn_1_page', wagtail.blocks.PageChooserBlock()), ('btn_2_text', wagtail.blocks.CharBlock()), ('btn_2_link', wagtail.blocks.URLBlock())])), ('cta_section_with_checklist', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock()), ('body', wagtail.blocks.ListBlock(child_block=wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock())]))), ('list_items', wagtail.blocks.ListBlock(child_block=wagtail.blocks.StructBlock([('item_text', wagtail.blocks.CharBlock())]))), ('btn_1_text', wagtail.blocks.CharBlock()), ('btn_1_page', wagtail.blocks.PageChooserBlock())]))], blank=True, null=True),
        ),
    ]
